var assert     = require('assert')
  , porExtenso = require('../lib/por-extenso')

it('should translate 10* in full correctly', function () {
  assert.equal(porExtenso(100), 'cem')
  assert.equal(porExtenso(101), 'cento e um')
  assert.equal(porExtenso(102), 'cento e dois')
  assert.equal(porExtenso(103), 'cento e três')
  assert.equal(porExtenso(104), 'cento e quatro')
  assert.equal(porExtenso(105), 'cento e cinco')
  assert.equal(porExtenso(106), 'cento e seis')
  assert.equal(porExtenso(107), 'cento e sete')
  assert.equal(porExtenso(108), 'cento e oito')
  assert.equal(porExtenso(109), 'cento e nove')
})

it('should translate 11* in full correctly', function () {
  assert.equal(porExtenso(110), 'cento e dez')
  assert.equal(porExtenso(111), 'cento e onze')
  assert.equal(porExtenso(112), 'cento e doze')
  assert.equal(porExtenso(113), 'cento e treze')
  assert.equal(porExtenso(114), 'cento e quatorze')
  assert.equal(porExtenso(115), 'cento e quinze')
  assert.equal(porExtenso(116), 'cento e dezesseis')
  assert.equal(porExtenso(117), 'cento e dezessete')
  assert.equal(porExtenso(118), 'cento e dezoito')
  assert.equal(porExtenso(119), 'cento e dezenove')
})

it('should translate 12* in full correctly', function () {
  assert.equal(porExtenso(120), 'cento e vinte')
  assert.equal(porExtenso(121), 'cento e vinte e um')
  assert.equal(porExtenso(122), 'cento e vinte e dois')
  assert.equal(porExtenso(123), 'cento e vinte e três')
  assert.equal(porExtenso(124), 'cento e vinte e quatro')
  assert.equal(porExtenso(125), 'cento e vinte e cinco')
  assert.equal(porExtenso(126), 'cento e vinte e seis')
  assert.equal(porExtenso(127), 'cento e vinte e sete')
  assert.equal(porExtenso(128), 'cento e vinte e oito')
  assert.equal(porExtenso(129), 'cento e vinte e nove')
})

it('should translate 13* in full correctly', function () {
  assert.equal(porExtenso(130), 'cento e trinta')
  assert.equal(porExtenso(131), 'cento e trinta e um')
  assert.equal(porExtenso(132), 'cento e trinta e dois')
  assert.equal(porExtenso(133), 'cento e trinta e três')
  assert.equal(porExtenso(134), 'cento e trinta e quatro')
  assert.equal(porExtenso(135), 'cento e trinta e cinco')
  assert.equal(porExtenso(136), 'cento e trinta e seis')
  assert.equal(porExtenso(137), 'cento e trinta e sete')
  assert.equal(porExtenso(138), 'cento e trinta e oito')
  assert.equal(porExtenso(139), 'cento e trinta e nove')
})

it('should translate 14* in full correctly', function () {
  assert.equal(porExtenso(140), 'cento e quarenta')
  assert.equal(porExtenso(141), 'cento e quarenta e um')
  assert.equal(porExtenso(142), 'cento e quarenta e dois')
  assert.equal(porExtenso(143), 'cento e quarenta e três')
  assert.equal(porExtenso(144), 'cento e quarenta e quatro')
  assert.equal(porExtenso(145), 'cento e quarenta e cinco')
  assert.equal(porExtenso(146), 'cento e quarenta e seis')
  assert.equal(porExtenso(147), 'cento e quarenta e sete')
  assert.equal(porExtenso(148), 'cento e quarenta e oito')
  assert.equal(porExtenso(149), 'cento e quarenta e nove')
})

it('should translate 15* in full correctly', function () {
  assert.equal(porExtenso(150), 'cento e cinquenta')
  assert.equal(porExtenso(151), 'cento e cinquenta e um')
  assert.equal(porExtenso(152), 'cento e cinquenta e dois')
  assert.equal(porExtenso(153), 'cento e cinquenta e três')
  assert.equal(porExtenso(154), 'cento e cinquenta e quatro')
  assert.equal(porExtenso(155), 'cento e cinquenta e cinco')
  assert.equal(porExtenso(156), 'cento e cinquenta e seis')
  assert.equal(porExtenso(157), 'cento e cinquenta e sete')
  assert.equal(porExtenso(158), 'cento e cinquenta e oito')
  assert.equal(porExtenso(159), 'cento e cinquenta e nove')
})

it('should translate 16* in full correctly', function () {
  assert.equal(porExtenso(160), 'cento e sessenta')
  assert.equal(porExtenso(161), 'cento e sessenta e um')
  assert.equal(porExtenso(162), 'cento e sessenta e dois')
  assert.equal(porExtenso(163), 'cento e sessenta e três')
  assert.equal(porExtenso(164), 'cento e sessenta e quatro')
  assert.equal(porExtenso(165), 'cento e sessenta e cinco')
  assert.equal(porExtenso(166), 'cento e sessenta e seis')
  assert.equal(porExtenso(167), 'cento e sessenta e sete')
  assert.equal(porExtenso(168), 'cento e sessenta e oito')
  assert.equal(porExtenso(169), 'cento e sessenta e nove')
})

it('should translate 17* in full correctly', function () {
  assert.equal(porExtenso(170), 'cento e setenta')
  assert.equal(porExtenso(171), 'cento e setenta e um')
  assert.equal(porExtenso(172), 'cento e setenta e dois')
  assert.equal(porExtenso(173), 'cento e setenta e três')
  assert.equal(porExtenso(174), 'cento e setenta e quatro')
  assert.equal(porExtenso(175), 'cento e setenta e cinco')
  assert.equal(porExtenso(176), 'cento e setenta e seis')
  assert.equal(porExtenso(177), 'cento e setenta e sete')
  assert.equal(porExtenso(178), 'cento e setenta e oito')
  assert.equal(porExtenso(179), 'cento e setenta e nove')
})

it('should translate 18* in full correctly', function () {
  assert.equal(porExtenso(180), 'cento e oitenta')
  assert.equal(porExtenso(181), 'cento e oitenta e um')
  assert.equal(porExtenso(182), 'cento e oitenta e dois')
  assert.equal(porExtenso(183), 'cento e oitenta e três')
  assert.equal(porExtenso(184), 'cento e oitenta e quatro')
  assert.equal(porExtenso(185), 'cento e oitenta e cinco')
  assert.equal(porExtenso(186), 'cento e oitenta e seis')
  assert.equal(porExtenso(187), 'cento e oitenta e sete')
  assert.equal(porExtenso(188), 'cento e oitenta e oito')
  assert.equal(porExtenso(189), 'cento e oitenta e nove')
})

it('should translate 19* in full correctly', function () {
  assert.equal(porExtenso(190), 'cento e noventa')
  assert.equal(porExtenso(191), 'cento e noventa e um')
  assert.equal(porExtenso(192), 'cento e noventa e dois')
  assert.equal(porExtenso(193), 'cento e noventa e três')
  assert.equal(porExtenso(194), 'cento e noventa e quatro')
  assert.equal(porExtenso(195), 'cento e noventa e cinco')
  assert.equal(porExtenso(196), 'cento e noventa e seis')
  assert.equal(porExtenso(197), 'cento e noventa e sete')
  assert.equal(porExtenso(198), 'cento e noventa e oito')
  assert.equal(porExtenso(199), 'cento e noventa e nove')
})

