var assert     = require('assert')
  , porExtenso = require('../lib/por-extenso')

it('should translate 20* in full correctly', function () {
  assert.equal(porExtenso(200), 'duzentos')
  assert.equal(porExtenso(201), 'duzentos e um')
  assert.equal(porExtenso(202), 'duzentos e dois')
  assert.equal(porExtenso(203), 'duzentos e três')
  assert.equal(porExtenso(204), 'duzentos e quatro')
  assert.equal(porExtenso(205), 'duzentos e cinco')
  assert.equal(porExtenso(206), 'duzentos e seis')
  assert.equal(porExtenso(207), 'duzentos e sete')
  assert.equal(porExtenso(208), 'duzentos e oito')
  assert.equal(porExtenso(209), 'duzentos e nove')
})

it('should translate 21* in full correctly', function () {
  assert.equal(porExtenso(210), 'duzentos e dez')
  assert.equal(porExtenso(211), 'duzentos e onze')
  assert.equal(porExtenso(212), 'duzentos e doze')
  assert.equal(porExtenso(213), 'duzentos e treze')
  assert.equal(porExtenso(214), 'duzentos e quatorze')
  assert.equal(porExtenso(215), 'duzentos e quinze')
  assert.equal(porExtenso(216), 'duzentos e dezesseis')
  assert.equal(porExtenso(217), 'duzentos e dezessete')
  assert.equal(porExtenso(218), 'duzentos e dezoito')
  assert.equal(porExtenso(219), 'duzentos e dezenove')
})

it('should translate 22* in full correctly', function () {
  assert.equal(porExtenso(220), 'duzentos e vinte')
  assert.equal(porExtenso(221), 'duzentos e vinte e um')
  assert.equal(porExtenso(222), 'duzentos e vinte e dois')
  assert.equal(porExtenso(223), 'duzentos e vinte e três')
  assert.equal(porExtenso(224), 'duzentos e vinte e quatro')
  assert.equal(porExtenso(225), 'duzentos e vinte e cinco')
  assert.equal(porExtenso(226), 'duzentos e vinte e seis')
  assert.equal(porExtenso(227), 'duzentos e vinte e sete')
  assert.equal(porExtenso(228), 'duzentos e vinte e oito')
  assert.equal(porExtenso(229), 'duzentos e vinte e nove')
})

it('should translate 23* in full correctly', function () {
  assert.equal(porExtenso(230), 'duzentos e trinta')
  assert.equal(porExtenso(231), 'duzentos e trinta e um')
  assert.equal(porExtenso(232), 'duzentos e trinta e dois')
  assert.equal(porExtenso(233), 'duzentos e trinta e três')
  assert.equal(porExtenso(234), 'duzentos e trinta e quatro')
  assert.equal(porExtenso(235), 'duzentos e trinta e cinco')
  assert.equal(porExtenso(236), 'duzentos e trinta e seis')
  assert.equal(porExtenso(237), 'duzentos e trinta e sete')
  assert.equal(porExtenso(238), 'duzentos e trinta e oito')
  assert.equal(porExtenso(239), 'duzentos e trinta e nove')
})

it('should translate 24* in full correctly', function () {
  assert.equal(porExtenso(240), 'duzentos e quarenta')
  assert.equal(porExtenso(241), 'duzentos e quarenta e um')
  assert.equal(porExtenso(242), 'duzentos e quarenta e dois')
  assert.equal(porExtenso(243), 'duzentos e quarenta e três')
  assert.equal(porExtenso(244), 'duzentos e quarenta e quatro')
  assert.equal(porExtenso(245), 'duzentos e quarenta e cinco')
  assert.equal(porExtenso(246), 'duzentos e quarenta e seis')
  assert.equal(porExtenso(247), 'duzentos e quarenta e sete')
  assert.equal(porExtenso(248), 'duzentos e quarenta e oito')
  assert.equal(porExtenso(249), 'duzentos e quarenta e nove')
})

it('should translate 25* in full correctly', function () {
  assert.equal(porExtenso(250), 'duzentos e cinquenta')
  assert.equal(porExtenso(251), 'duzentos e cinquenta e um')
  assert.equal(porExtenso(252), 'duzentos e cinquenta e dois')
  assert.equal(porExtenso(253), 'duzentos e cinquenta e três')
  assert.equal(porExtenso(254), 'duzentos e cinquenta e quatro')
  assert.equal(porExtenso(255), 'duzentos e cinquenta e cinco')
  assert.equal(porExtenso(256), 'duzentos e cinquenta e seis')
  assert.equal(porExtenso(257), 'duzentos e cinquenta e sete')
  assert.equal(porExtenso(258), 'duzentos e cinquenta e oito')
  assert.equal(porExtenso(259), 'duzentos e cinquenta e nove')
})

it('should translate 26* in full correctly', function () {
  assert.equal(porExtenso(260), 'duzentos e sessenta')
  assert.equal(porExtenso(261), 'duzentos e sessenta e um')
  assert.equal(porExtenso(262), 'duzentos e sessenta e dois')
  assert.equal(porExtenso(263), 'duzentos e sessenta e três')
  assert.equal(porExtenso(264), 'duzentos e sessenta e quatro')
  assert.equal(porExtenso(265), 'duzentos e sessenta e cinco')
  assert.equal(porExtenso(266), 'duzentos e sessenta e seis')
  assert.equal(porExtenso(267), 'duzentos e sessenta e sete')
  assert.equal(porExtenso(268), 'duzentos e sessenta e oito')
  assert.equal(porExtenso(269), 'duzentos e sessenta e nove')
})

it('should translate 27* in full correctly', function () {
  assert.equal(porExtenso(270), 'duzentos e setenta')
  assert.equal(porExtenso(271), 'duzentos e setenta e um')
  assert.equal(porExtenso(272), 'duzentos e setenta e dois')
  assert.equal(porExtenso(273), 'duzentos e setenta e três')
  assert.equal(porExtenso(274), 'duzentos e setenta e quatro')
  assert.equal(porExtenso(275), 'duzentos e setenta e cinco')
  assert.equal(porExtenso(276), 'duzentos e setenta e seis')
  assert.equal(porExtenso(277), 'duzentos e setenta e sete')
  assert.equal(porExtenso(278), 'duzentos e setenta e oito')
  assert.equal(porExtenso(279), 'duzentos e setenta e nove')
})

it('should translate 28* in full correctly', function () {
  assert.equal(porExtenso(280), 'duzentos e oitenta')
  assert.equal(porExtenso(281), 'duzentos e oitenta e um')
  assert.equal(porExtenso(282), 'duzentos e oitenta e dois')
  assert.equal(porExtenso(283), 'duzentos e oitenta e três')
  assert.equal(porExtenso(284), 'duzentos e oitenta e quatro')
  assert.equal(porExtenso(285), 'duzentos e oitenta e cinco')
  assert.equal(porExtenso(286), 'duzentos e oitenta e seis')
  assert.equal(porExtenso(287), 'duzentos e oitenta e sete')
  assert.equal(porExtenso(288), 'duzentos e oitenta e oito')
  assert.equal(porExtenso(289), 'duzentos e oitenta e nove')
})

it('should translate 29* in full correctly', function () {
  assert.equal(porExtenso(290), 'duzentos e noventa')
  assert.equal(porExtenso(291), 'duzentos e noventa e um')
  assert.equal(porExtenso(292), 'duzentos e noventa e dois')
  assert.equal(porExtenso(293), 'duzentos e noventa e três')
  assert.equal(porExtenso(294), 'duzentos e noventa e quatro')
  assert.equal(porExtenso(295), 'duzentos e noventa e cinco')
  assert.equal(porExtenso(296), 'duzentos e noventa e seis')
  assert.equal(porExtenso(297), 'duzentos e noventa e sete')
  assert.equal(porExtenso(298), 'duzentos e noventa e oito')
  assert.equal(porExtenso(299), 'duzentos e noventa e nove')
})

